"""PARTS 8-9 - AES-256-GCM ENCRYPTION / DECRYPTION.

Uses AES-256-GCM from the `cryptography` library (standard, audited).

    - confidentiality  (AES)
    - integrity        (GCM ciphertext authentication)
    - authentication   (GCM tag over plaintext + AAD)

Connects:
    - nonce:   12 bytes generated by the OS CSPRNG (fresh every operation;
               never reused with the same key → see api.py session policy).
    - AAD:     canonical JSON metadata, authenticated but NOT encrypted.

Errors:
    - InvalidTag / AuthenticationError on tamper or wrong key. Never fall
      back to plaintext.
"""

from __future__ import annotations

import json

from cryptography.exceptions import InvalidTag
from cryptography.hazmat.primitives.ciphers.aead import AESGCM

ALGORITHM = "AES-256-GCM"
NONCE_SIZE = 12
TAG_SIZE = 16

# Purpose tag embedded in AAD (see spec Part 9).
AAD_PURPOSE = "FISHRAND-DIARY-V1"


def canonical_aad(*, version: int = 4, algorithm: str = ALGORITHM, purpose: str = AAD_PURPOSE) -> bytes:
    """Deterministic canonical AAD bytes.

    Same fixed key ordering, UTF-8, minimal separators. Any change to these
    fields later makes decryption fail the GCM tag - by design.
    """
    return json.dumps(
        {
            "version": version,
            "algorithm": algorithm,
            "purpose": purpose,
        },
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=False,
    ).encode("utf-8")


def encrypt(key: bytes, nonce: bytes, plaintext: bytes, aad: bytes | None = None) -> bytes:
    """Encrypt+authenticate `plaintext` -> single blob (ciphertext || tag)."""
    if len(nonce) != NONCE_SIZE:
        raise ValueError(f"nonce must be {NONCE_SIZE} bytes")
    return AESGCM(key).encrypt(nonce, plaintext, aad or b"")


def decrypt(key: bytes, nonce: bytes, ciphertext_blob: bytes, aad: bytes | None = None) -> bytes:
    """Verify the GCM tag and decrypt.

    Raises InvalidTag (an AuthenticationError) if the tag does not verify;
    plaintext is only returned after successful authentication.
    """
    if len(nonce) != NONCE_SIZE:
        raise ValueError(f"nonce must be {NONCE_SIZE} bytes")
    return AESGCM(key).decrypt(nonce, ciphertext_blob, aad or b"")


__all__ = ["ALGORITHM", "NONCE_SIZE", "TAG_SIZE", "AAD_PURPOSE",
           "canonical_aad", "encrypt", "decrypt", "InvalidTag"]